advanced_section/advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("basic_app.urls")),
]

advanced_section/advcbv/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = "basic_app"

urlpatterns = [
    path('',views.index,name="index"),
    path('cbvpage',views.CBView.as_view(),name="cbvpage"),
    path('cbv',views.IndexView.as_view(),name="cbv"),
    path('schools',views.SchoolListView.as_view(),name="schools"),
    path('<pk>',views.SchoolDetailView.as_view(),name="detail"),


]

advanced_section/advcbv/basic_app/models.py
from django.db import models

class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=150)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=250)
    age = models.CharField(max_length=150)
    school = models.ForeignKey(School,related_name='students',on_delete=None)
    def __str__(self):
        return self.name

advanced_section/advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView
from basic_app.models import School, Student


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = School
    template_name = 'basic_app/school_details.html'


class CBView(View):
    def get(self,request):
        return render(request,'basic_app/index.html')

class IndexView(TemplateView):
    template_name = 'basic_app/cbv.html'
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = "SAMPLE INJECTION"
        return context


def index(request):
    context ={}
    return render(request,'basic_app/index.html',context)

advanced_section/advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home Page </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>
  <body>
      <header>
        <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'basic_app:schools' %}">Jithendra Kumar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarSupportedContent">

                <ul class="navbar-nav ml-auto">
                      <li class="nav-item ">
                                {% if request.path == '/schools' %}
                                <a class="nav-link active" href="{% url 'basic_app:schools' %}">School List  <span class="sr-only"></span></a>
                                {% else %}
                                <a class="nav-link " href="{% url 'basic_app:schools' %}">School List  <span class="sr-only"></span></a>
                                {% endif %}
                        </li>
                      </ul>
                </div>
            </div>
          </nav>
      </header>
      <div class="container">
          {% block body_block  %}
            <!-- body code goes here -->
          {% endblock  %}
      </div>


      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


  </body>
</html>

advanced_section/advcbv/basic_app/templates/basic_app/school_details.html
{% extends 'basic_app/basic_app_base.html'%}
  {% block body_block %}
    <h1>{{ school_detail.name | title}} School Details </h1>
      <table class="table table-striped table-hovered">
          <tr>
            <th>School Name </th>
            <td> {{ school_detail.name }}</td>
          </tr>
          <tr>
            <th>School Principal </th>
            <td> {{ school_detail.principal }}</td>
          </tr>
          <tr>
            <th>School Location </th>
            <td> {{ school_detail.location }}</td>
          </tr>
      </table>
      <h1> Studendt List </h1>
      <table class="table table-striped table-hovered table-bordered">
          <tr>
            <th>Student Name </th>
            <th>AGE</th>
          </tr>
          {% for student in school_detail.students.all  %}
            <tr>
              <th>{{ student.name }} </th>
              <th>who is {{ student.age }} years old.</th>
            </tr>
          {% endfor %}

      </table>


  {% endblock body_block %}

advanced_section/advcbv/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html'%}
  {% block body_block %}
    <h1 class="text-center">School List </h1>

    <ol>
      {% for school in schools %}
      <h2><li><a href="{{ school.id }}">  {{ school.name }} </a> </li></h2>
      {% endfor %}
    </ol>

  {% endblock  %}

advanced_section/advcbv/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home Page </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>
  <body>
      <div class="container">
          {% block body_block  %}
            <!-- body code goes here -->
          {% endblock  %}
      </div>
  </body>
</html>

advanced_section/advcbv/templates/basic_app/cbv.html
{% extends 'basic_app/base.html'%}
  {% block body_block %}
    <h1>CBV PAGE </h1>
    <h2>INJECTME EXAAMPLE : {{injectme}}</h2>

  {% endblock body_block %}

advanced_section/advcbv/templates/basic_app/index.html
{% extends 'basic_app/base.html'%}
  {% block body_block %}
    <h1>INDEX PAGE </h1>

  {% endblock body_block %}