level_five/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = "basic_app"

urlpatterns = [
    path('',views.index,name="index"),
    path('user_login/',views.user_login,name="user_login"),
    path('logout',views.user_logout,name="logout"),
    path('register',views.register,name="register"),
    path('special',views.special,name="special"),

]

level_five/level_five/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include("basic_app.urls")),

]

level_five/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=True)
    portfolio = models.URLField(blank=True)
    profile_image = models.ImageField(upload_to="profile_pics",blank=True)

    def __str__(self):
        return self.user.username

level_five/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    portfolio = forms.URLField(required=False)
    profile_image = forms.ImageField(required=False)

    class Meta():
        model = UserProfileInfo
        exclude = ("user",)

level_five/basic_app/views.py
from django.shortcuts import render,redirect
from basic_app.forms import UserForm,UserProfileInfoForm

#Login code goes here
from django.contrib.auth import login,logout,authenticate
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    context ={}
    return render(request,'basic_app/index.html',context)

def register(request):
    registered = False
    context = {'registered':registered}
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        user_profile = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and user_profile.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = user_profile.save(commit=False)
            profile.user = user
            if 'profile_image' in request.FILES:
                profile.profile_image = request.FILES['profile_image']
            profile.save()

            registered = True
        else:
            print(user_form.errors,user_profile.errors)
    else:
        user_form = UserForm()
        user_profile = UserProfileInfoForm()
    context = {'user_form':user_form,'user_profile':user_profile,'registered':registered}
    return render(request,'basic_app/registration.html',context)



def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username)
        print(password)
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return  HttpResponseRedirect(reverse('basic_app:index'))
            else:
                return HttpResponse("Account Not Active..!")
        else:
            print("Someone trying to login and Failed!")
            print("Username : {} and Password : {}".format(username,password))
            return HttpResponse("Invalid Login Details")
    else:
        return render(request,'basic_app/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('basic_app:user_login'))

@login_required
def special(request):
    return render(request,'basic_app/special.html')

level_five/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{% static 'basic_app/bootstrap.min.css' %}">
    <title>Home Page</title>
    <style>
      .header{
        background-color: teal;
      }
      .bg_gray{
        background-color: #eee;
        border-radius:5px;
        padding: 15px;
      }
      .header>.container>h3{color:#fff;padding:40px}
      .mr50{margin-top:20px;}
      .card{
        -webkit-box-shadow: 3px 4px 5px 0px rgba(0,0,0,0.4);
        -moz-box-shadow: 3px 4px 5px 0px rgba(0,0,0,0.4);
        box-shadow: 3px 4px 5px 0px rgba(0,0,0,0.4);
        background-color:teal;color:#fff;
        }
        .card_bg{
        background-color:green;color:#fff;
        }
        .card_bg_2{
        background-color:red;color:#fff;
        }
        #no_link{
            text-decoration: none;
            color:#fff;

            }
    </style>
  </head>
  <body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'basic_app:index' %}">Jithendra Kumar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse " id="navbarSupportedContent">

            <ul class="navbar-nav ml-auto">
                  <li class="nav-item ">
                            {% if request.path == '/' %}
                            <a class="nav-link active" href="{% url 'basic_app:index' %}">Home  <span class="sr-only"></span></a>
                            {% else %}
                            <a class="nav-link " href="{% url 'basic_app:index' %}">Home <span class="sr-only"></span></a>
                            {% endif %}

                    </li>

                    <li class="nav-item ">
                        {% if request.path == '/register' %}
                        <a class="nav-link active" href="{% url 'basic_app:register' %}">Signup <span class="sr-only"></span></a>
                        {% else %}
                        <a class="nav-link " href="{% url 'basic_app:register' %}">Signup <span class="sr-only"></span></a>
                        {% endif %}
                    </li>
                    <li class="nav-item ">
                        {% if request.path == '/special' %}
                        <a class="nav-link active" href="{% url 'basic_app:special' %}">Special Page <span class="sr-only"></span></a>
                        {% else %}
                        <a class="nav-link " href="{% url 'basic_app:special' %}">Special Page <span class="sr-only"></span></a>
                        {% endif %}
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item ">
                        <a class="nav-link " href="{% url 'basic_app:logout' %}">Logout <span class="sr-only"></span></a>
                    </li>
                    {% else %}

                    <li class="nav-item ">
                        {% if request.path == '/user_login' %}
                        <a class="nav-link active" href="{% url 'basic_app:user_login' %}">Login <span class="sr-only"></span></a>
                        {% else %}
                        <a class="nav-link " href="{% url 'basic_app:user_login' %}">Login <span class="sr-only"></span></a>
                        {% endif %}
                    </li>
                    {% endif %}
                  </ul>
            </div>
        </div>
      </nav>
    <!-- <div class="container-fluid header">
          <div class="container">
              <h3>What Do You Want To Do...!</h3>
          </div>
    </div> -->
    <div class="container">
          {% block body_block %}
          <!-- Body  code goes here  -->



          {% endblock  %}.
            <!-- Body  code ends here  -->
      </div>
      <div class="container">
        {%block footer_block%}
        <!-- footer blockquote starts here -->


        {% endblock  %}
        <!-- footer blockquote ends here -->

      </div>






    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script>
    $(document).ready(function(){
var li = document.getElementsByTagName("input");
// var lit = document.getElementsByTagName("textarea");
  for(i=0;i<li.length;i++){
     li[i].classList.add("form-control");
     // lit[i].classList.add("form-control");
  }
});

</script>
</body>
</html>

level_five/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
  {% block body_block %}
    <h1>Index Page</h1>

  {% endblock body_block %}

level_five/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
  {% block body_block %}
    <div class="row" >
      <div class="col-3"></div>
      <div class="col-5" style="background:#eee;padding:15px;margin-top:15%">
      <h1>Login Here....!</h1>
      <form class="" action="{% url 'basic_app:user_login' %}" method="post">
        {% csrf_token %}
          <div class="form-group">
              <label for="username">Username</label>
              <input type="text" name="username"  placeholder="Username" class="form-control">
          </div>
          <div class="form-group">
              <label for="password">Password</label>
              <input type="password" name="password"  placeholder="Password" class="form-control">
          </div>
          <div class="form-group">
              <input type="submit" name="submit"  value="Login" class="btn btn-success">
          </div>
      </form>

      </div>
    </div>

  {% endblock body_block %}

level_five/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
  {% block body_block %}
      {% if registered %}
          <h1>Thankyou For Registring!</h1>
      {% else %}
          <h1>Register Here!</h1>
          <h3>Fill out the form </h3>
          <form  method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{user_form.as_p}}
              {{user_profile.as_p}}
              <input type="submit" class="btn btn-success" name="submit" value="submit">
          </form>

        {% endif %}
  {% endblock body_block %}

level_five/templates/basic_app/special.html
{% extends 'basic_app/base.html' %}
  {% block body_block %}
    <h1>Hello This Is Special Page</h1>

  {% endblock body_block %}